'use strict';

var defaultIndex = {
    title: 'defaultIndex',
    timeFieldName: 'out.timestamp',
    fields: '[{"name":"out.ext.Sentado.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.biases.fashion","type":"boolean","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.time","type":"number","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.AT","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.type","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.thomasKilmann","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.type_hashCode","type":"number","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.score","type":"number","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.OrdenOpciones2","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.OrdenOpciones1","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.Respira.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.LuzIntermitente.keyword","type":"string","count":0,"scripted":false,' +
    '"indexed":true,"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.Llamo112.keyword","type":"string","count":0,"scripted":false,' +
    '"indexed":true,"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.location","type":"geo_point","count":0,"scripted":false,' +
    '"indexed":true,"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.DT.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.NotaINC","type":"number","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.RealizoHeimlich","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.RealizoHeimlich.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.ComproboRespiracion.keyword","type":"string","count":0,"scripted":false,' +
    '"indexed":true,"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.ProponeEsperar","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"_source","type":"_source","count":0,"scripted":false,"indexed":false,' +
    '"analyzed":false,"doc_values":false,"searchable":false,"aggregatable":false},' +
    '{"name":"out.ext.biases.gender","type":"boolean","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.TelEscondido.keyword","type":"string","count":0,"scripted":false,' +
    '"indexed":true,"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.HablandoTelefono","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.IniciarTimerInconsciente","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.VieneAmbulancia","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.gameplayId_hashCode","type":"number","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.Sentado","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.OrdenOpciones1.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.INC.keyword","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.ElectrodosConectados","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.DT","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.Respira","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.TerminoINC","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.event","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.timestamp","type":"date","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.LuzIntermitente","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.INC","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.Ayuda","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.TemporizadorConsciencia.keyword","type":"string","count":0,"scripted":false,' +
    '"indexed":true,"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.NotaDT","type":"number","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.progress","type":"number","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.TerminoINC.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.PosicionDeSeguridad.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.DesfibriladorColocado","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.InicioTos","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.DefibriladorAbierto.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.BotonIntermitente.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.stored","type":"date","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.TerminoDT.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.Estimulado.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.thomasKilmann.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.biases.race","type":"boolean","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.OrdenOpciones2.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.gameplayId","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.response.keyword","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.TerminoAT","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.Desfibrilador.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.type.keyword","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.event_hashCode","type":"number","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.AT.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.ProponeEsperar.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.target.keyword","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.name.keyword","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.Llamo112","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.IniciarTimerInconsciente.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.TemporizadorConsciencia","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.TerminoAT.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.success","type":"boolean","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.PosicionDeSeguridad","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.name","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.DesfibriladorColocado.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.DefibriladorAbierto","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.Ayuda.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.Desfibrilador","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.NotaAT","type":"number","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
    '"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.HablandoTelefono.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.InicioTos.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.biases.otherSocial","type":"boolean","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.biases.ability","type":"boolean","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.gameplayId.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.event.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.BotonIntermitente","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.TelEscondido","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.VieneAmbulancia.keyword","type":"string","count":0,"scripted":false,' +
    '"indexed":true,"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.ComproboRespiracion","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.target","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.ElectrodosConectados.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.target_hashCode","type":"number","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.response","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
    '"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.TerminoDT","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"out.ext.biases.occupation","type":"boolean","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"out.ext.Estimulado","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false},' +
    '{"name":"_id","type":"string","count":0,"scripted":false,"indexed":false,"analyzed":false,' +
    '"doc_values":false,"searchable":false,"aggregatable":false},' +
    '{"name":"_type","type":"string","count":0,"scripted":false,"indexed":false,"analyzed":false,' +
    '"doc_values":false,"searchable":true,"aggregatable":true},' +
    '{"name":"_index","type":"string","count":0,"scripted":false,"indexed":false,"analyzed":false,' +
    '"doc_values":false,"searchable":false,"aggregatable":false},' +
    '{"name":"_score","type":"number","count":0,"scripted":false,"indexed":false,"analyzed":false,' +
    '"doc_values":false,"searchable":false,"aggregatable":false},' +
    '{"name":"tkscripted","type":"number","count":0,"scripted":true,"script":' +
    '"if (doc[\'out.ext.thomasKilmann.keyword\'].value == \\\"avoiding\\\") return 1;if (doc[\'out.ext.thomasKilmann.keyword\'].value ' +
    '== \\\"competing\\\") ' +
    'return 2;if (doc[\'out.ext.thomasKilmann.keyword\'].value == \\\"acomodating\\\") return 3;' +
    'if (doc[\'out.ext.thomasKilmann.keyword\'].value == \\\"compromising\\\") return 4;' +
    'if (doc[\'out.ext.thomasKilmann.keyword\'].value == \\\"collaborating\\\") return 5;' +
    'return 0;","lang":"painless","indexed":false,"analyzed":false,"doc_values":false,' +
    '"searchable":true,"aggregatable":true},' +
    '{"name":"bias_value_false","type":"number","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"bias_value_true","type":"number","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"bias_type.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":false,"doc_values":true,"searchable":true,"aggregatable":true},' +
    '{"name":"bias_type","type":"string","count":0,"scripted":false,"indexed":true,' +
    '"analyzed":true,"doc_values":false,"searchable":true,"aggregatable":false}' +
    ']',
    fieldFormatMap: '{"tkscripted":{"id":"number"}}'
};

module.exports = defaultIndex;
