'use strict';

var defaultIndex = {
        title: 'defaultIndex',
        timeFieldName: 'stored',
        fields: '[{"name":"type","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
        '"doc_values":false},{"name":"gameplayId","type":"string","count":0,"scripted":false,"indexed":true,' +
        '"analyzed":true,"doc_values":false},{"name":"Estimulado.keyword","type":"string","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"type_hashCode",' +
        '"type":"number","count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},' +
        '{"name":"DT","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
        '"doc_values":false},{"name":"ComproboRespiracion","type":"string","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":true,"doc_values":false},{"name":"score","type":"number","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"response.keyword",' +
        '"type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},' +
        '{"name":"Desfibrilador","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
        '"doc_values":false},{"name":"Desfibrilador.keyword","type":"string","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":false,"doc_values":true},{"name":"type.keyword","type":"string","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"Ayuda","type":"string",' +
        '"count":0,"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},{"name":"event_hashCode",' +
        '"type":"number","count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},' +
        '{"name":"Ayuda.keyword","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
        '"doc_values":true},{"name":"HablandoTelefono","type":"string","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":true,"doc_values":false},{"name":"target.keyword","type":"string",' +
        '"count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"name.keyword",' +
        '"type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},' +
        '{"name":"IniciarTimerInconsciente.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
        '"analyzed":false,"doc_values":true},{"name":"Sentado.keyword","type":"string","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":false,"doc_values":true},{"name":"versionId","type":"string","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},{"name":"VieneAmbulancia",' +
        '"type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},' +
        '{"name":"PosicionDeSeguridad.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
        '"analyzed":false,"doc_values":true},{"name":"success","type":"boolean","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":false,"doc_values":true},{"name":"Sentado","type":"string","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},{"name":"name","type":"string",' +
        '"count":0,"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},{"name":"_source",' +
        '"type":"_source","count":0,"scripted":false,"indexed":false,"analyzed":false,"doc_values":false},' +
        '{"name":"Llamo112","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
        '"doc_values":false},{"name":"INC","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
        '"doc_values":false},{"name":"OrdenOpciones1.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
        '"analyzed":false,"doc_values":true},{"name":"gameplayId_hashCode","type":"number","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":false,"doc_values":true},{"name":"Estimulado","type":"string","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},{"name":"Respira","type":"string",' +
        '"count":0,"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},{"name":"OrdenOpciones2",' +
        '"type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},' +
        '{"name":"PosicionDeSeguridad","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
        '"doc_values":false},{"name":"OrdenOpciones1","type":"string","count":0,"scripted":false,"indexed":true,' +
        '"analyzed":true,"doc_values":false},{"name":"HablandoTelefono.keyword","type":"string","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"INC.keyword","type":"string",' +
        '"count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"Respira.keyword",' +
        '"type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},' +
        '{"name":"VieneAmbulancia.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
        '"analyzed":false,"doc_values":true},{"name":"gameplayId.keyword","type":"string","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"Llamo112.keyword",' +
        '"type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},' +
        '{"name":"event","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,' +
        '"doc_values":false},{"name":"ComproboRespiracion.keyword","type":"string","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":false,"doc_values":true},{"name":"versionId.keyword","type":"string",' +
        '"count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"timestamp",' +
        '"type":"date","count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},' +
        '{"name":"event.keyword","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
        '"doc_values":true},{"name":"TemporizadorConsciencia","type":"string","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":true,"doc_values":false},{"name":"DT.keyword","type":"string","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"target","type":"string",' +
        '"count":0,"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},{"name":"NotaDT",' +
        '"type":"string","count":0,"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},' +
        '{"name":"NotaDT.keyword","type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
        '"doc_values":true},{"name":"IniciarTimerInconsciente","type":"string","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":true,"doc_values":false},{"name":"target_hashCode","type":"number","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"response","type":"string",' +
        '"count":0,"scripted":false,"indexed":true,"analyzed":true,"doc_values":false},' +
        '{"name":"TemporizadorConsciencia.keyword","type":"string","count":0,"scripted":false,"indexed":true,' +
        '"analyzed":false,"doc_values":true},{"name":"stored","type":"date","count":0,"scripted":false,' +
        '"indexed":true,"analyzed":false,"doc_values":true},{"name":"progress","type":"number","count":0,' +
        '"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},{"name":"OrdenOpciones2.keyword",' +
        '"type":"string","count":0,"scripted":false,"indexed":true,"analyzed":false,"doc_values":true},' +
        '{"name":"time","type":"number","count":0,"scripted":false,"indexed":true,"analyzed":false,' +
        '"doc_values":true},{"name":"_id","type":"string","count":0,"scripted":false,"indexed":false,' +
        '"analyzed":false,"doc_values":false},{"name":"_type","type":"string","count":0,"scripted":false,' +
        '"indexed":false,"analyzed":false,"doc_values":false},{"name":"_index","type":"string","count":0,' +
        '"scripted":false,"indexed":false,"analyzed":false,"doc_values":false},{"name":"_score","type":"number",' +
        '"count":0,"scripted":false,"indexed":false,"analyzed":false,"doc_values":false}]'
    };

module.exports = defaultIndex;